version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.mockk:mockk
    versions:
    - "> 1.9.3.kotlin12, < 1.9.4"
  - dependency-name: io.mockk:mockk-dsl-jvm
    versions:
    - "> 1.9.3.kotlin12, < 1.9.4"
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-plugin
    versions:
    - "< 1.4, >= 1.3.a"
  - dependency-name: org.jetbrains.kotlin:kotlin-reflect
    versions:
    - "< 1.4, >= 1.3.a"
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - "< 1.4, >= 1.3.a"
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib-jdk8
    versions:
    - "< 1.4, >= 1.3.a"
  - dependency-name: org.jetbrains.kotlin:kotlin-test
    versions:
    - "< 1.4, >= 1.3.a"
  - dependency-name: org.jetbrains.kotlin:kotlin-test-junit
    versions:
    - "< 1.4, >= 1.3.a"
  - dependency-name: org.jetbrains.dokka:dokka-maven-plugin
    versions:
    - 1.4.20-dev-65
