name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    uses: ./.github/workflows/maven-build.yml

  deploy:
    name: Deploy
    needs: build
    if: github.repository == 'gantsign/doxia-sink-api-ktx'
    uses: ./.github/workflows/maven-deploy.yml
    secrets: inherit
