name: Release
on:
  push:
    tags:
      - '*'
env:
  JAVA_TOOL_OPTIONS: >-
    -XX:TieredStopAtLevel=1
    -XX:+UseParallelGC
    -Dstyle.color=always
    -Djansi.force=true

jobs:
  build:
    name: Maven build
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'
      - name: Build with Maven
        run: |-
          export GIT_TAG="${GITHUB_REF#refs/tags/}"
          .github/scripts/build.sh
      - name: Code coverage report
        uses: codecov/codecov-action@v2.1.0

  deploy:
    name: Maven deploy
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'
      - name: Install GPG key
        run: |-
          gpg --batch --import-options import-show --import << EOF
          ${{ secrets.GPG_KEY }}
          EOF
      - name: Deploy with Maven
        run: |-
          export GIT_TAG="${GITHUB_REF#refs/tags/}"
          .github/scripts/deploy.sh
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Delete GPG secret key
        if: ${{ always() }}
        run: gpg --batch --yes --delete-secret-keys ${{ secrets.GPG_KEY_NAME }} || true
      - name: Delete GPG public key
        if: ${{ always() }}
        run: gpg --batch --yes --delete-keys ${{ secrets.GPG_KEY_NAME }}
